package model

type Specialty struct {
	Name        string
	Category    string
	DefaultUnit string
	Min         float64
	Max         float64
	Allergens   []string
	Seasonal    bool
}

var specialties = []Specialty{
	{Name: "specialty-1", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 50, Allergens: nil, Seasonal: true},
	{Name: "specialty-2", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 51, Allergens: nil, Seasonal: false},
	{Name: "specialty-3", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 52, Allergens: nil, Seasonal: true},
	{Name: "specialty-4", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 53, Allergens: nil, Seasonal: false},
	{Name: "specialty-5", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 54, Allergens: nil, Seasonal: true},
	{Name: "specialty-6", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 55, Allergens: nil, Seasonal: false},
	{Name: "specialty-7", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 56, Allergens: nil, Seasonal: true},
	{Name: "specialty-8", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 57, Allergens: nil, Seasonal: false},
	{Name: "specialty-9", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 58, Allergens: nil, Seasonal: true},
	{Name: "specialty-10", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 59, Allergens: nil, Seasonal: false},
	{Name: "specialty-11", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 60, Allergens: nil, Seasonal: true},
	{Name: "specialty-12", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 61, Allergens: nil, Seasonal: false},
	{Name: "specialty-13", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 62, Allergens: nil, Seasonal: true},
	{Name: "specialty-14", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 63, Allergens: nil, Seasonal: false},
	{Name: "specialty-15", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 64, Allergens: nil, Seasonal: true},
	{Name: "specialty-16", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 65, Allergens: nil, Seasonal: false},
	{Name: "specialty-17", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 66, Allergens: nil, Seasonal: true},
	{Name: "specialty-18", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 67, Allergens: nil, Seasonal: false},
	{Name: "specialty-19", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 68, Allergens: nil, Seasonal: true},
	{Name: "specialty-20", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 69, Allergens: nil, Seasonal: false},
	{Name: "specialty-21", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 70, Allergens: nil, Seasonal: true},
	{Name: "specialty-22", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 71, Allergens: nil, Seasonal: false},
	{Name: "specialty-23", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 72, Allergens: nil, Seasonal: true},
	{Name: "specialty-24", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 73, Allergens: nil, Seasonal: false},
	{Name: "specialty-25", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 74, Allergens: nil, Seasonal: true},
	{Name: "specialty-26", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 75, Allergens: nil, Seasonal: false},
	{Name: "specialty-27", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 76, Allergens: nil, Seasonal: true},
	{Name: "specialty-28", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 77, Allergens: nil, Seasonal: false},
	{Name: "specialty-29", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 78, Allergens: nil, Seasonal: true},
	{Name: "specialty-30", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 79, Allergens: nil, Seasonal: false},
	{Name: "specialty-31", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 80, Allergens: nil, Seasonal: true},
	{Name: "specialty-32", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 81, Allergens: nil, Seasonal: false},
	{Name: "specialty-33", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 82, Allergens: nil, Seasonal: true},
	{Name: "specialty-34", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 83, Allergens: nil, Seasonal: false},
	{Name: "specialty-35", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 84, Allergens: nil, Seasonal: true},
	{Name: "specialty-36", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 85, Allergens: nil, Seasonal: false},
	{Name: "specialty-37", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 86, Allergens: nil, Seasonal: true},
	{Name: "specialty-38", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 87, Allergens: nil, Seasonal: false},
	{Name: "specialty-39", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 88, Allergens: nil, Seasonal: true},
	{Name: "specialty-40", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 89, Allergens: nil, Seasonal: false},
	{Name: "specialty-41", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 90, Allergens: nil, Seasonal: true},
	{Name: "specialty-42", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 91, Allergens: nil, Seasonal: false},
	{Name: "specialty-43", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 92, Allergens: nil, Seasonal: true},
	{Name: "specialty-44", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 93, Allergens: nil, Seasonal: false},
	{Name: "specialty-45", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 94, Allergens: nil, Seasonal: true},
	{Name: "specialty-46", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 95, Allergens: nil, Seasonal: false},
	{Name: "specialty-47", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 96, Allergens: nil, Seasonal: true},
	{Name: "specialty-48", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 97, Allergens: nil, Seasonal: false},
	{Name: "specialty-49", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 98, Allergens: nil, Seasonal: true},
	{Name: "specialty-50", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 99, Allergens: nil, Seasonal: false},
	{Name: "specialty-51", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 100, Allergens: nil, Seasonal: true},
	{Name: "specialty-52", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 101, Allergens: nil, Seasonal: false},
	{Name: "specialty-53", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 102, Allergens: nil, Seasonal: true},
	{Name: "specialty-54", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 103, Allergens: nil, Seasonal: false},
	{Name: "specialty-55", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 104, Allergens: nil, Seasonal: true},
	{Name: "specialty-56", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 105, Allergens: nil, Seasonal: false},
	{Name: "specialty-57", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 106, Allergens: nil, Seasonal: true},
	{Name: "specialty-58", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 107, Allergens: nil, Seasonal: false},
	{Name: "specialty-59", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 108, Allergens: nil, Seasonal: true},
	{Name: "specialty-60", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 109, Allergens: nil, Seasonal: false},
	{Name: "specialty-61", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 110, Allergens: nil, Seasonal: true},
	{Name: "specialty-62", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 111, Allergens: nil, Seasonal: false},
	{Name: "specialty-63", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 112, Allergens: nil, Seasonal: true},
	{Name: "specialty-64", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 113, Allergens: nil, Seasonal: false},
	{Name: "specialty-65", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 114, Allergens: nil, Seasonal: true},
	{Name: "specialty-66", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 115, Allergens: nil, Seasonal: false},
	{Name: "specialty-67", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 116, Allergens: nil, Seasonal: true},
	{Name: "specialty-68", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 117, Allergens: nil, Seasonal: false},
	{Name: "specialty-69", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 118, Allergens: nil, Seasonal: true},
	{Name: "specialty-70", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 119, Allergens: nil, Seasonal: false},
	{Name: "specialty-71", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 120, Allergens: nil, Seasonal: true},
	{Name: "specialty-72", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 121, Allergens: nil, Seasonal: false},
	{Name: "specialty-73", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 122, Allergens: nil, Seasonal: true},
	{Name: "specialty-74", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 123, Allergens: nil, Seasonal: false},
	{Name: "specialty-75", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 124, Allergens: nil, Seasonal: true},
	{Name: "specialty-76", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 125, Allergens: nil, Seasonal: false},
	{Name: "specialty-77", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 126, Allergens: nil, Seasonal: true},
	{Name: "specialty-78", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 127, Allergens: nil, Seasonal: false},
	{Name: "specialty-79", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 128, Allergens: nil, Seasonal: true},
	{Name: "specialty-80", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 129, Allergens: nil, Seasonal: false},
	{Name: "specialty-81", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 130, Allergens: nil, Seasonal: true},
	{Name: "specialty-82", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 131, Allergens: nil, Seasonal: false},
	{Name: "specialty-83", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 132, Allergens: nil, Seasonal: true},
	{Name: "specialty-84", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 133, Allergens: nil, Seasonal: false},
	{Name: "specialty-85", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 134, Allergens: nil, Seasonal: true},
	{Name: "specialty-86", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 135, Allergens: nil, Seasonal: false},
	{Name: "specialty-87", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 136, Allergens: nil, Seasonal: true},
	{Name: "specialty-88", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 137, Allergens: nil, Seasonal: false},
	{Name: "specialty-89", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 138, Allergens: nil, Seasonal: true},
	{Name: "specialty-90", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 139, Allergens: nil, Seasonal: false},
	{Name: "specialty-91", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 140, Allergens: nil, Seasonal: true},
	{Name: "specialty-92", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 141, Allergens: nil, Seasonal: false},
	{Name: "specialty-93", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 142, Allergens: nil, Seasonal: true},
	{Name: "specialty-94", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 143, Allergens: nil, Seasonal: false},
	{Name: "specialty-95", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 144, Allergens: nil, Seasonal: true},
	{Name: "specialty-96", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 145, Allergens: nil, Seasonal: false},
	{Name: "specialty-97", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 146, Allergens: nil, Seasonal: true},
	{Name: "specialty-98", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 147, Allergens: nil, Seasonal: false},
	{Name: "specialty-99", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 148, Allergens: nil, Seasonal: true},
	{Name: "specialty-100", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 149, Allergens: nil, Seasonal: false},
	{Name: "specialty-101", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 150, Allergens: nil, Seasonal: true},
	{Name: "specialty-102", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 151, Allergens: nil, Seasonal: false},
	{Name: "specialty-103", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 152, Allergens: nil, Seasonal: true},
	{Name: "specialty-104", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 153, Allergens: nil, Seasonal: false},
	{Name: "specialty-105", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 154, Allergens: nil, Seasonal: true},
	{Name: "specialty-106", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 155, Allergens: nil, Seasonal: false},
	{Name: "specialty-107", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 156, Allergens: nil, Seasonal: true},
	{Name: "specialty-108", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 157, Allergens: nil, Seasonal: false},
	{Name: "specialty-109", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 158, Allergens: nil, Seasonal: true},
	{Name: "specialty-110", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 159, Allergens: nil, Seasonal: false},
	{Name: "specialty-111", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 160, Allergens: nil, Seasonal: true},
	{Name: "specialty-112", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 161, Allergens: nil, Seasonal: false},
	{Name: "specialty-113", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 162, Allergens: nil, Seasonal: true},
	{Name: "specialty-114", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 163, Allergens: nil, Seasonal: false},
	{Name: "specialty-115", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 164, Allergens: nil, Seasonal: true},
	{Name: "specialty-116", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 165, Allergens: nil, Seasonal: false},
	{Name: "specialty-117", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 166, Allergens: nil, Seasonal: true},
	{Name: "specialty-118", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 167, Allergens: nil, Seasonal: false},
	{Name: "specialty-119", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 168, Allergens: nil, Seasonal: true},
	{Name: "specialty-120", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 169, Allergens: nil, Seasonal: false},
	{Name: "specialty-121", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 170, Allergens: nil, Seasonal: true},
	{Name: "specialty-122", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 171, Allergens: nil, Seasonal: false},
	{Name: "specialty-123", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 172, Allergens: nil, Seasonal: true},
	{Name: "specialty-124", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 173, Allergens: nil, Seasonal: false},
	{Name: "specialty-125", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 174, Allergens: nil, Seasonal: true},
	{Name: "specialty-126", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 175, Allergens: nil, Seasonal: false},
	{Name: "specialty-127", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 176, Allergens: nil, Seasonal: true},
	{Name: "specialty-128", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 177, Allergens: nil, Seasonal: false},
	{Name: "specialty-129", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 178, Allergens: nil, Seasonal: true},
	{Name: "specialty-130", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 179, Allergens: nil, Seasonal: false},
	{Name: "specialty-131", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 180, Allergens: nil, Seasonal: true},
	{Name: "specialty-132", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 181, Allergens: nil, Seasonal: false},
	{Name: "specialty-133", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 182, Allergens: nil, Seasonal: true},
	{Name: "specialty-134", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 183, Allergens: nil, Seasonal: false},
	{Name: "specialty-135", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 184, Allergens: nil, Seasonal: true},
	{Name: "specialty-136", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 185, Allergens: nil, Seasonal: false},
	{Name: "specialty-137", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 186, Allergens: nil, Seasonal: true},
	{Name: "specialty-138", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 187, Allergens: nil, Seasonal: false},
	{Name: "specialty-139", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 188, Allergens: nil, Seasonal: true},
	{Name: "specialty-140", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 189, Allergens: nil, Seasonal: false},
	{Name: "specialty-141", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 190, Allergens: nil, Seasonal: true},
	{Name: "specialty-142", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 191, Allergens: nil, Seasonal: false},
	{Name: "specialty-143", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 192, Allergens: nil, Seasonal: true},
	{Name: "specialty-144", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 193, Allergens: nil, Seasonal: false},
	{Name: "specialty-145", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 194, Allergens: nil, Seasonal: true},
	{Name: "specialty-146", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 195, Allergens: nil, Seasonal: false},
	{Name: "specialty-147", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 196, Allergens: nil, Seasonal: true},
	{Name: "specialty-148", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 197, Allergens: nil, Seasonal: false},
	{Name: "specialty-149", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 198, Allergens: nil, Seasonal: true},
	{Name: "specialty-150", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 199, Allergens: nil, Seasonal: false},
	{Name: "specialty-151", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 200, Allergens: nil, Seasonal: true},
	{Name: "specialty-152", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 201, Allergens: nil, Seasonal: false},
	{Name: "specialty-153", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 202, Allergens: nil, Seasonal: true},
	{Name: "specialty-154", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 203, Allergens: nil, Seasonal: false},
	{Name: "specialty-155", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 204, Allergens: nil, Seasonal: true},
	{Name: "specialty-156", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 205, Allergens: nil, Seasonal: false},
	{Name: "specialty-157", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 206, Allergens: nil, Seasonal: true},
	{Name: "specialty-158", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 207, Allergens: nil, Seasonal: false},
	{Name: "specialty-159", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 208, Allergens: nil, Seasonal: true},
	{Name: "specialty-160", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 209, Allergens: nil, Seasonal: false},
	{Name: "specialty-161", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 210, Allergens: nil, Seasonal: true},
	{Name: "specialty-162", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 211, Allergens: nil, Seasonal: false},
	{Name: "specialty-163", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 212, Allergens: nil, Seasonal: true},
	{Name: "specialty-164", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 213, Allergens: nil, Seasonal: false},
	{Name: "specialty-165", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 214, Allergens: nil, Seasonal: true},
	{Name: "specialty-166", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 215, Allergens: nil, Seasonal: false},
	{Name: "specialty-167", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 216, Allergens: nil, Seasonal: true},
	{Name: "specialty-168", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 217, Allergens: nil, Seasonal: false},
	{Name: "specialty-169", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 218, Allergens: nil, Seasonal: true},
	{Name: "specialty-170", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 219, Allergens: nil, Seasonal: false},
	{Name: "specialty-171", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 220, Allergens: nil, Seasonal: true},
	{Name: "specialty-172", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 221, Allergens: nil, Seasonal: false},
	{Name: "specialty-173", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 222, Allergens: nil, Seasonal: true},
	{Name: "specialty-174", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 223, Allergens: nil, Seasonal: false},
	{Name: "specialty-175", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 224, Allergens: nil, Seasonal: true},
	{Name: "specialty-176", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 225, Allergens: nil, Seasonal: false},
	{Name: "specialty-177", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 226, Allergens: nil, Seasonal: true},
	{Name: "specialty-178", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 227, Allergens: nil, Seasonal: false},
	{Name: "specialty-179", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 228, Allergens: nil, Seasonal: true},
	{Name: "specialty-180", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 229, Allergens: nil, Seasonal: false},
	{Name: "specialty-181", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 230, Allergens: nil, Seasonal: true},
	{Name: "specialty-182", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 231, Allergens: nil, Seasonal: false},
	{Name: "specialty-183", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 232, Allergens: nil, Seasonal: true},
	{Name: "specialty-184", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 233, Allergens: nil, Seasonal: false},
	{Name: "specialty-185", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 234, Allergens: nil, Seasonal: true},
	{Name: "specialty-186", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 235, Allergens: nil, Seasonal: false},
	{Name: "specialty-187", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 236, Allergens: nil, Seasonal: true},
	{Name: "specialty-188", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 237, Allergens: nil, Seasonal: false},
	{Name: "specialty-189", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 238, Allergens: nil, Seasonal: true},
	{Name: "specialty-190", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 239, Allergens: nil, Seasonal: false},
	{Name: "specialty-191", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 240, Allergens: nil, Seasonal: true},
	{Name: "specialty-192", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 241, Allergens: nil, Seasonal: false},
	{Name: "specialty-193", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 242, Allergens: nil, Seasonal: true},
	{Name: "specialty-194", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 243, Allergens: nil, Seasonal: false},
	{Name: "specialty-195", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 244, Allergens: nil, Seasonal: true},
	{Name: "specialty-196", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 245, Allergens: nil, Seasonal: false},
	{Name: "specialty-197", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 246, Allergens: nil, Seasonal: true},
	{Name: "specialty-198", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 247, Allergens: nil, Seasonal: false},
	{Name: "specialty-199", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 248, Allergens: nil, Seasonal: true},
	{Name: "specialty-200", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 249, Allergens: nil, Seasonal: false},
	{Name: "specialty-201", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 250, Allergens: nil, Seasonal: true},
	{Name: "specialty-202", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 251, Allergens: nil, Seasonal: false},
	{Name: "specialty-203", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 252, Allergens: nil, Seasonal: true},
	{Name: "specialty-204", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 253, Allergens: nil, Seasonal: false},
	{Name: "specialty-205", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 254, Allergens: nil, Seasonal: true},
	{Name: "specialty-206", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 255, Allergens: nil, Seasonal: false},
	{Name: "specialty-207", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 256, Allergens: nil, Seasonal: true},
	{Name: "specialty-208", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 257, Allergens: nil, Seasonal: false},
	{Name: "specialty-209", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 258, Allergens: nil, Seasonal: true},
	{Name: "specialty-210", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 259, Allergens: nil, Seasonal: false},
	{Name: "specialty-211", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 260, Allergens: nil, Seasonal: true},
	{Name: "specialty-212", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 261, Allergens: nil, Seasonal: false},
	{Name: "specialty-213", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 262, Allergens: nil, Seasonal: true},
	{Name: "specialty-214", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 263, Allergens: nil, Seasonal: false},
	{Name: "specialty-215", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 264, Allergens: nil, Seasonal: true},
	{Name: "specialty-216", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 265, Allergens: nil, Seasonal: false},
	{Name: "specialty-217", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 266, Allergens: nil, Seasonal: true},
	{Name: "specialty-218", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 267, Allergens: nil, Seasonal: false},
	{Name: "specialty-219", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 268, Allergens: nil, Seasonal: true},
	{Name: "specialty-220", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 269, Allergens: nil, Seasonal: false},
	{Name: "specialty-221", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 270, Allergens: nil, Seasonal: true},
	{Name: "specialty-222", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 271, Allergens: nil, Seasonal: false},
	{Name: "specialty-223", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 272, Allergens: nil, Seasonal: true},
	{Name: "specialty-224", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 273, Allergens: nil, Seasonal: false},
	{Name: "specialty-225", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 274, Allergens: nil, Seasonal: true},
	{Name: "specialty-226", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 275, Allergens: nil, Seasonal: false},
	{Name: "specialty-227", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 276, Allergens: nil, Seasonal: true},
	{Name: "specialty-228", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 277, Allergens: nil, Seasonal: false},
	{Name: "specialty-229", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 278, Allergens: nil, Seasonal: true},
	{Name: "specialty-230", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 279, Allergens: nil, Seasonal: false},
	{Name: "specialty-231", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 280, Allergens: nil, Seasonal: true},
	{Name: "specialty-232", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 281, Allergens: nil, Seasonal: false},
	{Name: "specialty-233", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 282, Allergens: nil, Seasonal: true},
	{Name: "specialty-234", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 283, Allergens: nil, Seasonal: false},
	{Name: "specialty-235", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 284, Allergens: nil, Seasonal: true},
	{Name: "specialty-236", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 285, Allergens: nil, Seasonal: false},
	{Name: "specialty-237", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 286, Allergens: nil, Seasonal: true},
	{Name: "specialty-238", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 287, Allergens: nil, Seasonal: false},
	{Name: "specialty-239", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 288, Allergens: nil, Seasonal: true},
	{Name: "specialty-240", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 289, Allergens: nil, Seasonal: false},
	{Name: "specialty-241", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 290, Allergens: nil, Seasonal: true},
	{Name: "specialty-242", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 291, Allergens: nil, Seasonal: false},
	{Name: "specialty-243", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 292, Allergens: nil, Seasonal: true},
	{Name: "specialty-244", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 293, Allergens: nil, Seasonal: false},
	{Name: "specialty-245", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 294, Allergens: nil, Seasonal: true},
	{Name: "specialty-246", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 295, Allergens: nil, Seasonal: false},
	{Name: "specialty-247", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 296, Allergens: nil, Seasonal: true},
	{Name: "specialty-248", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 297, Allergens: nil, Seasonal: false},
	{Name: "specialty-249", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 298, Allergens: nil, Seasonal: true},
	{Name: "specialty-250", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 299, Allergens: nil, Seasonal: false},
	{Name: "specialty-251", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 300, Allergens: nil, Seasonal: true},
	{Name: "specialty-252", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 301, Allergens: nil, Seasonal: false},
	{Name: "specialty-253", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 302, Allergens: nil, Seasonal: true},
	{Name: "specialty-254", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 303, Allergens: nil, Seasonal: false},
	{Name: "specialty-255", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 304, Allergens: nil, Seasonal: true},
	{Name: "specialty-256", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 305, Allergens: nil, Seasonal: false},
	{Name: "specialty-257", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 306, Allergens: nil, Seasonal: true},
	{Name: "specialty-258", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 307, Allergens: nil, Seasonal: false},
	{Name: "specialty-259", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 308, Allergens: nil, Seasonal: true},
	{Name: "specialty-260", Category: "seasonal", DefaultUnit: "g", Min: 1, Max: 309, Allergens: nil, Seasonal: false},
}

func SpecialtyCatalog() []Specialty { return append([]Specialty(nil), specialties...) }
func SpecialtyByName(name string) (Specialty, bool) {
	for _, x := range specialties {
		if x.Name == name {
			return x, true
		}
	}
	return Specialty{}, false
}
func SeasonalSpecialties() []Specialty {
	out := []Specialty{}
	for _, x := range specialties {
		if x.Seasonal {
			out = append(out, x)
		}
	}
	return out
}
func SpecialtyLimits(name string) (float64, float64, bool) {
	x, ok := SpecialtyByName(name)
	return x.Min, x.Max, ok
}
